# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    gym(
      workspace: "iOS_Sample_Architecture.xcworkspace",
      configuration: "Debug",
      scheme: "UIKit_Sample_Architecture",   # specify the name of the .ipa file to generate (including file extension)
      destination: "platform=iOS Simulator,name=iPhone 13",
      sdk: "iphonesimulator",
      skip_archive: true # use SDK as the name or path of the base SDK when building the project.
    )
  end
end
